version: "3.8"

services:
  build-gpl-image:
    build:
      context: ./dsm232
    volumes:
      - ./build:/env/ott/images
  build-dsm260-image:
    build:
      context: ./dsm260
    volumes:
      - ./build_dsm260:/env/dsm260_GPL/dongle/img
  make-cameohax-image:
    build:
      context: ./dsm232
    command: ./gshock/gshock.sh
    volumes:
      - ./build:/env/ott/images:ro
      - ./gshock:/env/ott/gshock:ro
      - ./app:/env/ott/app
